import Head from "next/head";
import CustomShinyText from "~/components/custom/CustomShinyText";
import CustomSplashCursor from "~/components/custom/CustomSplashCursor";
import Button from "~/components/ui/Button";
import SpotlightCard from "~/components/ui/SpotLightCard";
import Title from "~/components/ui/Title";
import Text from "~/components/ui/Text";
import Link from "~/components/ui/Link";
import SkillBox from "~/components/ui/SkillBox";
import TECH_STACK from "~/data/techStack";

export default function Home() {
  console.log(TECH_STACK);
  return (
    <>
      <Head>
        <title>Nicolas Lopez</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col gap-y-5 bg-black px-10 text-white">
        {/* Hero section */}
        <section className="flex min-h-screen flex-col items-center justify-center">
          {/* profile info */}
          <article className="text flex flex-col text-center lg:text-left">
            <Text className="text-3xl font-bold">Hi, I'm Nicolás Andrés!</Text>
            <CustomShinyText
              className="text-5xl font-bold"
              text="FULLSTACK DEVELOPER"
            />
          </article>
          {/* Actions */}
          <article className="flex gap-3">
            <Button>Contact Me</Button>
            <CustomSplashCursor />
          </article>
        </section>

        {/* About me section */}
        <section className="min-h-screen">
          <Title className="text-3xl font-bold">About me</Title>
          <Text>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi
            adipisci tenetur facere tempore hic doloremque quidem recusandae id
            in fugit voluptatum, eveniet ea esse quasi, voluptatem, voluptate
            sed laudantium quisquam.
          </Text>
        </section>

        {/* My tech stack */}
        <section className="min-h-screen">
          <Title className="text-3xl font-bold">My tech stack</Title>
          {TECH_STACK.map(([category, items]) => (
            <div>
              <Title className="text-xl">{category}</Title>
              <div className="flex gap-6 flex-wrap">
                {items.map(({ Icon, skill }) => (
                  <SkillBox Icon={Icon} skill={skill} />
                ))}
              </div>
            </div>
          ))}
        </section>

        {/* My projects */}
        <section className="min-h-screen">
          <Title className="text-3xl font-bold">My projects</Title>
          {/* Whatsapp Clone */}
          <SpotlightCard className="" spotlightColor="rgba(255, 255, 255, 0.2)">
            <img
              src="https://i.scdn.co/image/ab67616d0000b273d9985092cd88bffd97653b58"
              width={500}
              height={500}
              alt="Picture of the author"
            />
            <a href="/">
              <Title>Whatsapp clone</Title>
            </a>
            <Text>a whatsapp clone made by me</Text>
            <Link href="/">See source code</Link>
          </SpotlightCard>
          {/* Whatsapp Clone */}
          <SpotlightCard className="" spotlightColor="rgba(255, 255, 255, 0.2)">
            <img
              src="https://i.scdn.co/image/ab67616d0000b273d9985092cd88bffd97653b58"
              width={500}
              height={500}
              alt="Picture of the author"
            />
            <a href="/">
              <Title>Whatsapp clone</Title>
            </a>
            <Text>a whatsapp clone made by me</Text>
            <Link href="/">See source code</Link>
          </SpotlightCard>
          {/* Whatsapp Clone */}
          <SpotlightCard className="" spotlightColor="rgba(255, 255, 255, 0.2)">
            <img
              src="https://i.scdn.co/image/ab67616d0000b273d9985092cd88bffd97653b58"
              width={500}
              height={500}
              alt="Picture of the author"
            />
            <a href="/">
              <Title>Whatsapp clone</Title>
            </a>
            <Text>a whatsapp clone made by me</Text>
            <Link href="/">See source code</Link>
          </SpotlightCard>
        </section>
      </main>
    </>
  );
}
