import Head from "next/head";
import CustomShinyText from "~/components/custom/CustomShinyText";
import Button from "~/components/ui/Button";
import Text from "~/components/ui/Text";
import Link from "~/components/ui/Link";
import SkillBox from "~/components/ui/SkillBox";
import TECH_STACK from "~/data/techStack";
import MY_STATS from "~/data/MyStats";
import MY_PROJECTS from "~/data/myProjects";
import CustomGlareOver from "~/components/custom/CustomGlareOver";
import MY_EXPERIENCE from "~/data/myExperience";
import CustomSplashCursor from "~/components/custom/CustomSplashCursor";
import { FaGithub, FaLinkedin } from "react-icons/fa";
import MY_REFERENCES from "~/data/myReferences";
import { BiArrowToRight } from "react-icons/bi";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col gap-y-5 bg-black px-10 text-white md:px-20 lg:px-40 xl:px-100">
        {/* Hero section */}
        <section className="my-10 flex min-h-screen flex-col items-center justify-center">
          {/* profile info */}
          <article className="text flex flex-col text-center lg:text-left">
            <Text className="text-3xl font-bold">Hi, I'm Nicolás Andrés!</Text>
            <CustomShinyText
              className="text-5xl font-bold"
              text="FULLSTACK DEVELOPER"
            />
          </article>
          {/* Actions */}
          <article className="flex justify-start gap-3">
            <CustomSplashCursor />
          </article>
        </section>

        {/* About me section */}
        <section className="my-10 flex flex-col gap-7">
          <div>
            <h1 className="my-2 text-3xl font-bold">ABOUT ME</h1>
            <Text>
              Hi, there! I'm a fullstack dev from Colombia with over one year of
              experience in the IT industry, though I've been coding personal
              projects regularly for over 3 years. My expertise lies in
              developing apps using React and typescript.
            </Text>
            <div className="mt-4 flex gap-3">
              {MY_REFERENCES.map(({ Icon, label, link }) => (
                <a
                  key={label}
                  href={link}
                  className="group flex gap-2 rounded-lg border border-gray-600 bg-black/40 px-4 py-2 text-sm font-medium text-gray-300 backdrop-blur-sm transition hover:border-gray-400 hover:text-white hover:shadow-[0_0_10px_rgba(255,255,255,0.3)]"
                >
                  <Icon className="size-5" />
                  {label}
                  <BiArrowToRight className="size-5 transform transition-transform duration-300 group-hover:translate-x-1" />
                </a>
              ))}
            </div>
          </div>
          <div className="flex gap-14">
            {MY_STATS.map(([category, items]) => (
              <div key={category} className="flex flex-col">
                <span className="text-5xl font-bold">{items.amount}</span>
                <span className="text-md w-30 text-gray-300">
                  {items.label}
                </span>
              </div>
            ))}
          </div>
        </section>

        {/* My experience section */}
        <section className="my-10 flex flex-col gap-7">
          <div>
            <h1 className="my-2 text-3xl font-bold">MY EXPERIENCE</h1>
          </div>
          <div>
            {MY_EXPERIENCE.map(
              ({ label, description, timestamp, techStack }) => (
                <div className="flex flex-col gap-5 border-l-4 px-4">
                  <h1 className="text-xl font-bold">{label}</h1>
                  <Text>{description}</Text>
                  <div className="flex flex-col gap-3 md:flex-row md:justify-between">
                    <div className="flex gap-3">
                      {techStack.map((Tech) => (
                        <Tech className="size-7" />
                      ))}
                    </div>
                    <Text>{timestamp}</Text>
                  </div>
                </div>
              ),
            )}
          </div>
        </section>

        {/* My tech stack */}
        <section className="my-4">
          <h1 className="my-2 text-3xl font-bold">MY TECH STACK</h1>
          {TECH_STACK.map(([category, items]) => (
            <div key={category}>
              <h1 className="my-2 text-xl">{`→ ${category}`}</h1>
              <div className="flex flex-wrap gap-2">
                {items.map(({ Icon, skill }) => (
                  <SkillBox key={skill} Icon={Icon} skill={skill} />
                ))}
              </div>
            </div>
          ))}
        </section>

        {/* My projects */}
        <section className="my-10 mb-30 flex flex-col gap-4">
          <h1 className="my-2 text-3xl font-bold">MY PROJECTS</h1>
          <div className="flex flex-col flex-wrap gap-8 md:gap-x-1 md:gap-y-3 lg:flex-row xl:gap-4">
            {MY_PROJECTS.map(
              ({ description, name, repoLink, pageLink, stack, img }) => (
                <CustomGlareOver key={name} className="flex flex-col gap-5 p-6">
                  <div>
                    <img
                      src={img}
                      className="h-60 w-full rounded object-cover object-center"
                      alt="Picture of the project"
                    />
                    <h1 className="my-3 h-10 text-lg font-bold">{name}</h1>
                    <Text className="h-17">{description}</Text>
                  </div>
                  <div className="flex justify-between">
                    <Link href={repoLink}>See source code</Link>
                    <Link href={pageLink}>See</Link>
                  </div>
                  <div className="flex gap-3">
                    {stack.map((Tech) => (
                      <Tech className="size-7" />
                    ))}
                  </div>
                </CustomGlareOver>
              ),
            )}
          </div>
        </section>
      </main>
    </>
  );
}
